-- ============================================================
-- Southern Smiles — Historical Data Import
-- Generated: 2026-03-21 22:43:29
-- Stat entries: 134
-- OIC log entries: 35
-- ============================================================

-- IMPORTANT: Replace these placeholder UUIDs with the actual
-- auth.users UUIDs after creating the users in Supabase.
-- You can find them in the Supabase dashboard under Authentication > Users.

-- Step 1: Set these variables to your actual user UUIDs
DO $$
DECLARE
  shakally_id uuid;
  odalis_id uuid;
  lesley_id uuid;
  evelis_id uuid;
BEGIN
  -- Look up profile IDs by email (adjust emails as needed)
  SELECT id INTO shakally_id FROM profiles WHERE email ILIKE '%shakally%' OR email ILIKE '%monzer%' OR role = 'admin' LIMIT 1;
  SELECT id INTO odalis_id FROM profiles WHERE email ILIKE '%odalis%' LIMIT 1;
  SELECT id INTO lesley_id FROM profiles WHERE email ILIKE '%lesley%' LIMIT 1;
  SELECT id INTO evelis_id FROM profiles WHERE email ILIKE '%evelis%' LIMIT 1;

  -- Verify we found all profiles
  IF shakally_id IS NULL THEN RAISE EXCEPTION 'Could not find Shakally profile. Create auth users first.'; END IF;
  IF odalis_id IS NULL THEN RAISE EXCEPTION 'Could not find Odalis profile. Create auth users first.'; END IF;
  IF lesley_id IS NULL THEN RAISE EXCEPTION 'Could not find Lesley profile. Create auth users first.'; END IF;
  IF evelis_id IS NULL THEN RAISE EXCEPTION 'Could not find Evelis profile. Create auth users first.'; END IF;

  RAISE NOTICE 'Found all profiles: Shakally=%, Odalis=%, Lesley=%, Evelis=%', shakally_id, odalis_id, lesley_id, evelis_id;

  -- ============================================================
  -- Employee Post Assignments
  -- ============================================================
  -- Evelis → Receptionist
  INSERT INTO employee_posts (profile_id, post_id) VALUES (evelis_id, 'a0000001-0000-0000-0000-000000000001') ON CONFLICT (profile_id, post_id) DO NOTHING;
  -- Lesley → Scheduling Coordinator
  INSERT INTO employee_posts (profile_id, post_id) VALUES (lesley_id, 'a0000002-0000-0000-0000-000000000002') ON CONFLICT (profile_id, post_id) DO NOTHING;
  -- Lesley → PR Officer
  INSERT INTO employee_posts (profile_id, post_id) VALUES (lesley_id, 'a0000006-0000-0000-0000-000000000006') ON CONFLICT (profile_id, post_id) DO NOTHING;
  -- Odalis → Financial Coordinator
  INSERT INTO employee_posts (profile_id, post_id) VALUES (odalis_id, 'a0000003-0000-0000-0000-000000000003') ON CONFLICT (profile_id, post_id) DO NOTHING;
  -- Odalis → TX Coordinator
  INSERT INTO employee_posts (profile_id, post_id) VALUES (odalis_id, 'a0000004-0000-0000-0000-000000000004') ON CONFLICT (profile_id, post_id) DO NOTHING;
  -- Dr. Shakally → Doctor
  INSERT INTO employee_posts (profile_id, post_id) VALUES (shakally_id, 'a0000005-0000-0000-0000-000000000005') ON CONFLICT (profile_id, post_id) DO NOTHING;

  -- ============================================================
  -- Stat Entries (134 records)
  -- ============================================================
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000001-0000-0000-0000-000000000001', evelis_id, '2025-12-29', 0.0, NULL, 0.0, 'normal', 'affluence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000001-0000-0000-0000-000000000001', evelis_id, '2026-02-02', 50.0, 0.0, 0.0, 'normal', 'non_existence', 'Find a comm line., Make yourself known., Discover what is needed or wanted., Do, produce and/or present it.') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000001-0000-0000-0000-000000000001', evelis_id, '2026-02-16', 54.0, 50.0, 8.0, 'normal', 'normal', 'If a stat increased, what cased it to? how can we better incorporate it?') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000001-0000-0000-0000-000000000001', evelis_id, '2026-02-23', 185.0, 54.0, 242.5926, 'affluence', 'normal', 'If a stat increased, what cased it to? how can we better incorporate it?') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000001-0000-0000-0000-000000000001', evelis_id, '2026-03-02', 95.0, 185.0, -48.6486, 'non_existence', 'emergency', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000001-0000-0000-0000-000000000001', evelis_id, '2026-03-09', 0.0, 95.0, -100.0, 'non_existence', 'non_existence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000001-0000-0000-0000-000000000001', evelis_id, '2026-03-16', 0.0, 0.0, 0.0, 'normal', 'non_existence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000002-0000-0000-0000-000000000002', evelis_id, '2025-12-29', 0.0, NULL, 0.0, 'normal', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000002-0000-0000-0000-000000000002', evelis_id, '2026-02-02', 0.0, 0.0, 0.0, 'normal', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000002-0000-0000-0000-000000000002', evelis_id, '2026-03-02', 0.0, 0.0, 0.0, 'normal', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000002-0000-0000-0000-000000000002', evelis_id, '2026-03-09', 8.0, 0.0, 0.0, 'normal', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000002-0000-0000-0000-000000000002', evelis_id, '2026-03-16', 8.0, 8.0, 0.0, 'emergency', 'emergency', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000003-0000-0000-0000-000000000003', lesley_id, '2025-12-29', 0.0, NULL, 0.0, 'normal', 'affluence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000003-0000-0000-0000-000000000003', lesley_id, '2026-01-05', 0.54, 0.0, 0.0, 'normal', 'non_existence', 'Find a comm line., Make yourself known., Discover what is needed or wanted., Do, produce and/or present it.') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000003-0000-0000-0000-000000000003', lesley_id, '2026-01-12', 0.6258, 0.54, 15.8889, 'normal', 'normal', 'Don’t change anything., Ethics are very mild : Dont freak out over little things, If a stat increased, what cased it to? how can we better incorporate it?, If a stat decreased, why and how can we fix it?') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000003-0000-0000-0000-000000000003', lesley_id, '2026-01-19', 0.7871, 0.6258, 25.775, 'affluence', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000003-0000-0000-0000-000000000003', lesley_id, '2026-01-26', 0.6675, 0.7871, -15.195, 'danger', 'emergency', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000003-0000-0000-0000-000000000003', lesley_id, '2026-02-02', 0.6825, 0.6675, 2.2472, 'normal', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000003-0000-0000-0000-000000000003', lesley_id, '2026-02-09', 0.7825, 0.6825, 14.652, 'normal', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000003-0000-0000-0000-000000000003', lesley_id, '2026-02-16', 0.76, 0.7825, -2.8754, 'emergency', 'emergency', 'Promote and PRODUCE!') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000003-0000-0000-0000-000000000003', lesley_id, '2026-02-23', 0.895, 0.76, 17.7632, 'normal', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000003-0000-0000-0000-000000000003', lesley_id, '2026-03-02', 0.9367, 0.895, 4.6592, 'normal', 'affluence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000003-0000-0000-0000-000000000003', lesley_id, '2026-03-09', 0.8775, 0.9367, -6.3201, 'emergency', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000003-0000-0000-0000-000000000003', lesley_id, '2026-03-16', 1.0, 0.8775, 13.9601, 'normal', 'normal', 'Don’t change anything.') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000003-0000-0000-0000-000000000003', lesley_id, '2026-03-16', 1.0, 1.0, 0.0, 'emergency', 'normal', 'Don’t change anything.') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000004-0000-0000-0000-000000000004', lesley_id, '2025-12-29', 0.0, NULL, 0.0, 'normal', 'non_existence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000004-0000-0000-0000-000000000004', lesley_id, '2026-01-05', 0.51, 0.0, 0.0, 'normal', 'non_existence', 'Find a comm line., Make yourself known., Discover what is needed or wanted., Do, produce and/or present it.') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000004-0000-0000-0000-000000000004', lesley_id, '2026-01-12', 0.375, 0.51, -26.4706, 'danger', 'danger', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000004-0000-0000-0000-000000000004', lesley_id, '2026-01-19', 0.7388, 0.375, 97.0133, 'affluence', 'affluence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000004-0000-0000-0000-000000000004', lesley_id, '2026-01-26', 0.83, 0.7388, 12.3443, 'normal', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000004-0000-0000-0000-000000000004', lesley_id, '2026-02-02', 0.61, 0.83, -26.506, 'danger', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000004-0000-0000-0000-000000000004', lesley_id, '2026-02-09', 0.8, 0.61, 31.1475, 'affluence', 'affluence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000004-0000-0000-0000-000000000004', lesley_id, '2026-02-16', 0.53, 0.8, -33.75, 'danger', 'emergency', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000004-0000-0000-0000-000000000004', lesley_id, '2026-02-23', 0.8125, 0.53, 53.3019, 'affluence', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000004-0000-0000-0000-000000000004', lesley_id, '2026-03-02', 0.6667, 0.8125, -17.9446, 'danger', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000004-0000-0000-0000-000000000004', lesley_id, '2026-03-09', 0.7075, 0.6667, 6.1197, 'normal', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000004-0000-0000-0000-000000000004', lesley_id, '2026-03-16', 0.3333, 0.7075, -52.8905, 'non_existence', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000004-0000-0000-0000-000000000004', lesley_id, '2026-03-16', 1.0, 0.3333, 200.03, 'affluence', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000005-0000-0000-0000-000000000005', odalis_id, '2025-12-29', 0.0, NULL, 0.0, 'normal', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000005-0000-0000-0000-000000000005', odalis_id, '2026-01-05', 20525.9, 0.0, 0.0, 'normal', 'non_existence', 'Find a comm line., Make yourself known., Discover what is needed or wanted., Do, produce and/or present it.') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000005-0000-0000-0000-000000000005', odalis_id, '2026-01-12', 8390.0, 20525.9, -59.1248, 'non_existence', 'danger', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000005-0000-0000-0000-000000000005', odalis_id, '2026-01-19', 31965.0, 8390.0, 280.9893, 'affluence', 'affluence', '1. Economize: What areas need better Finical Control?, Pay every bill: Which bills are you going to pay?, Invest the remainder in service facilities: What should we buy?, What caused the Condition of Affluence? How can we  strengthen it?') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000005-0000-0000-0000-000000000005', odalis_id, '2026-01-26', 27746.0, 31965.0, -13.1988, 'emergency', 'emergency', 'Promote and PRODUCE!') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000005-0000-0000-0000-000000000005', odalis_id, '2026-02-02', 8042.31, 27746.0, -71.0145, 'non_existence', 'non_existence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000005-0000-0000-0000-000000000005', odalis_id, '2026-02-09', 13682.0, 8042.31, 70.1253, 'affluence', 'affluence', '1. Economize: What areas need better Finical Control?, Pay every bill: Which bills are you going to pay?') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000005-0000-0000-0000-000000000005', odalis_id, '2026-02-16', 3506.33, 13682.0, -74.3727, 'non_existence', 'danger', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000005-0000-0000-0000-000000000005', odalis_id, '2026-02-23', 32277.9, 3506.33, 820.5608, 'affluence', 'affluence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000005-0000-0000-0000-000000000005', odalis_id, '2026-03-02', 10131.53, 32277.9, -68.6116, 'non_existence', 'normal', 'Don’t change anything.') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000005-0000-0000-0000-000000000005', odalis_id, '2026-03-09', 23658.66, 10131.53, 133.5152, 'affluence', 'affluence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000005-0000-0000-0000-000000000005', odalis_id, '2026-03-16', 15612.0, 23658.66, -34.0115, 'danger', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000006-0000-0000-0000-000000000006', odalis_id, '2025-12-29', 0.0, NULL, 0.0, 'normal', 'emergency', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000006-0000-0000-0000-000000000006', odalis_id, '2026-01-05', 88534.88, 0.0, 0.0, 'normal', 'non_existence', 'Find a comm line., Make yourself known., Discover what is needed or wanted., Do, produce and/or present it.') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000006-0000-0000-0000-000000000006', odalis_id, '2026-01-12', 94490.0, 88534.88, 6.7263, 'emergency', 'emergency', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000006-0000-0000-0000-000000000006', odalis_id, '2026-01-19', 94255.0, 94490.0, -0.2487, 'normal', 'emergency', 'Promote and PRODUCE!, Change your operating basis, Economize, Prepare to deliver., Stiffen discipline') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000006-0000-0000-0000-000000000006', odalis_id, '2026-01-26', 105731.0, 94255.0, 12.1755, 'emergency', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000006-0000-0000-0000-000000000006', odalis_id, '2026-02-02', 103600.74, 105731.0, -2.0148, 'normal', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000006-0000-0000-0000-000000000006', odalis_id, '2026-02-09', 104267.0, 103600.74, 0.6431, 'emergency', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000006-0000-0000-0000-000000000006', odalis_id, '2026-02-16', 103332.61, 104267.0, -0.8962, 'normal', 'emergency', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000006-0000-0000-0000-000000000006', odalis_id, '2026-02-23', 120659.96, 103332.61, 16.7685, 'danger', 'emergency', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000006-0000-0000-0000-000000000006', odalis_id, '2026-03-09', 115624.82, 120659.96, -4.173, 'normal', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000006-0000-0000-0000-000000000006', odalis_id, '2026-03-16', 117504.0, 115624.82, 1.6252, 'emergency', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000007-0000-0000-0000-000000000007', odalis_id, '2025-12-29', 0.0, NULL, 0.0, 'normal', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000007-0000-0000-0000-000000000007', odalis_id, '2026-01-05', 1006.695, 0.0, 0.0, 'normal', 'non_existence', 'Find a comm line., Make yourself known., Discover what is needed or wanted., Do, produce and/or present it.') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000007-0000-0000-0000-000000000007', odalis_id, '2026-01-12', 372.93, 1006.695, -62.955, 'non_existence', 'non_existence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000007-0000-0000-0000-000000000007', odalis_id, '2026-01-19', 1559.0, 372.93, 318.0409, 'affluence', 'affluence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000007-0000-0000-0000-000000000007', odalis_id, '2026-01-26', 1296.0, 1559.0, -16.8698, 'danger', 'emergency', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000007-0000-0000-0000-000000000007', odalis_id, '2026-02-02', 393.11, 1296.0, -69.6674, 'non_existence', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000007-0000-0000-0000-000000000007', odalis_id, '2026-02-09', 2189.12, 393.11, 456.8721, 'affluence', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000007-0000-0000-0000-000000000007', odalis_id, '2026-02-16', 212.48, 2189.12, -90.2938, 'non_existence', 'danger', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000007-0000-0000-0000-000000000007', odalis_id, '2026-02-23', 1291.0, 212.48, 507.5866, 'affluence', 'affluence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000007-0000-0000-0000-000000000007', odalis_id, '2026-03-02', 2189.12, 1291.0, 69.5678, 'affluence', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000007-0000-0000-0000-000000000007', odalis_id, '2026-03-09', 1028.64, 2189.12, -53.0113, 'non_existence', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000007-0000-0000-0000-000000000007', odalis_id, '2026-03-16', 780.6, 1028.64, -24.1134, 'danger', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000008-0000-0000-0000-000000000008', odalis_id, '2025-12-29', 0.0, NULL, 0.0, 'normal', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000008-0000-0000-0000-000000000008', odalis_id, '2026-01-05', 2.0, 0.0, 0.0, 'normal', 'non_existence', 'Find a comm line., Make yourself known., Discover what is needed or wanted., Do, produce and/or present it.') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000008-0000-0000-0000-000000000008', odalis_id, '2026-01-12', 2.0, 2.0, 0.0, 'emergency', 'emergency', 'Promote and PRODUCE!, Change your operating basis, Economize, Prepare to deliver., Stiffen discipline') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000008-0000-0000-0000-000000000008', odalis_id, '2026-01-19', 8.0, 2.0, 300.0, 'affluence', 'affluence', '1. Economize: What areas need better Finical Control?, Pay every bill: Which bills are you going to pay?, Invest the remainder in service facilities: What should we buy?, What caused the Condition of Affluence? How can we  strengthen it?') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000008-0000-0000-0000-000000000008', odalis_id, '2026-01-26', 13.0, 8.0, 62.5, 'affluence', 'affluence', '1. Economize: What areas need better Finical Control?, Pay every bill: Which bills are you going to pay?, Invest the remainder in service facilities: What should we buy?, What caused the Condition of Affluence? How can we  strengthen it?') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000008-0000-0000-0000-000000000008', odalis_id, '2026-02-02', 4.0, 13.0, -69.2308, 'non_existence', 'danger', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000008-0000-0000-0000-000000000008', odalis_id, '2026-02-09', 4.0, 4.0, 0.0, 'emergency', 'emergency', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000008-0000-0000-0000-000000000008', odalis_id, '2026-02-16', 0.0, 4.0, -100.0, 'non_existence', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000008-0000-0000-0000-000000000008', odalis_id, '2026-02-23', 1.0, 0.0, 0.0, 'normal', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000008-0000-0000-0000-000000000008', odalis_id, '2026-03-02', 4.0, 1.0, 300.0, 'affluence', 'normal', 'Don’t change anything.') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000008-0000-0000-0000-000000000008', odalis_id, '2026-03-09', 5.0, 4.0, 25.0, 'affluence', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000008-0000-0000-0000-000000000008', odalis_id, '2026-03-16', 3.0, 5.0, -40.0, 'danger', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000009-0000-0000-0000-000000000009', odalis_id, '2025-12-29', 0.0, NULL, 0.0, 'normal', 'affluence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000009-0000-0000-0000-000000000009', odalis_id, '2026-01-05', 0.59, 0.0, 0.0, 'normal', 'non_existence', 'Find a comm line., Make yourself known., Discover what is needed or wanted., Do, produce and/or present it.') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000009-0000-0000-0000-000000000009', odalis_id, '2026-01-12', 0.315, 0.59, -46.6102, 'non_existence', 'danger', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000009-0000-0000-0000-000000000009', odalis_id, '2026-01-19', 0.1036, 0.315, -67.1111, 'non_existence', 'danger', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000009-0000-0000-0000-000000000009', odalis_id, '2026-01-26', 0.4879, 0.1036, 370.9459, 'affluence', 'affluence', '1. Economize: What areas need better Finical Control?, Pay every bill: Which bills are you going to pay?, Invest the remainder in service facilities: What should we buy?, What caused the Condition of Affluence? How can we  strengthen it?') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000009-0000-0000-0000-000000000009', odalis_id, '2026-02-02', 0.454, 0.4879, -6.9481, 'emergency', 'emergency', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000009-0000-0000-0000-000000000009', odalis_id, '2026-02-09', 0.42, 0.454, -7.489, 'emergency', 'emergency', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000009-0000-0000-0000-000000000009', odalis_id, '2026-02-16', 0.46, 0.42, 9.5238, 'normal', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000009-0000-0000-0000-000000000009', odalis_id, '2026-02-23', 0.6647, 0.46, 44.5, 'affluence', 'affluence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000009-0000-0000-0000-000000000009', odalis_id, '2026-03-02', 0.6947, 0.6647, 4.5133, 'normal', 'normal', 'Don’t change anything.') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000009-0000-0000-0000-000000000009', odalis_id, '2026-03-09', 0.7831, 0.6947, 12.7249, 'normal', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000009-0000-0000-0000-000000000009', odalis_id, '2026-03-16', 0.4545, 0.7831, -41.9614, 'non_existence', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000010-0000-0000-0000-000000000010', shakally_id, '2026-01-05', 0.0, NULL, 0.0, 'normal', 'affluence', 'What caused the Condition of Affluence? How can we  strengthen it?') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000010-0000-0000-0000-000000000010', shakally_id, '2026-01-12', 10249.0, 0.0, 0.0, 'normal', 'affluence', '1. Economize: What areas need better Finical Control?, Pay every bill: Which bills are you going to pay?, Invest the remainder in service facilities: What should we buy?, What caused the Condition of Affluence? How can we  strengthen it?') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000010-0000-0000-0000-000000000010', shakally_id, '2026-01-19', 28436.0, 10249.0, 177.4515, 'affluence', 'affluence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000010-0000-0000-0000-000000000010', shakally_id, '2026-01-26', 14159.0, 28436.0, -50.2075, 'non_existence', 'affluence', '1. Economize: What areas need better Finical Control?, Pay every bill: Which bills are you going to pay?, Invest the remainder in service facilities: What should we buy?, What caused the Condition of Affluence? How can we  strengthen it?') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000010-0000-0000-0000-000000000010', shakally_id, '2026-02-02', 15966.0, 14159.0, 12.7622, 'normal', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000010-0000-0000-0000-000000000010', shakally_id, '2026-02-09', 14875.0, 15966.0, -6.8333, 'emergency', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000010-0000-0000-0000-000000000010', shakally_id, '2026-02-16', 11883.0, 14875.0, -20.1143, 'danger', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000010-0000-0000-0000-000000000010', shakally_id, '2026-02-23', 27996.75, 11883.0, 135.6034, 'affluence', 'affluence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000010-0000-0000-0000-000000000010', shakally_id, '2026-03-02', 3891.0, 27996.75, -86.102, 'non_existence', 'non_existence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000010-0000-0000-0000-000000000010', shakally_id, '2026-03-09', 15442.0, 3891.0, 296.8646, 'affluence', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000010-0000-0000-0000-000000000010', shakally_id, '2026-03-16', 23974.0, 15442.0, 55.2519, 'affluence', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000011-0000-0000-0000-000000000011', lesley_id, '2025-12-29', 0.0, NULL, 0.0, 'normal', 'affluence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000011-0000-0000-0000-000000000011', lesley_id, '2026-01-05', 15.0, 0.0, 0.0, 'normal', 'non_existence', 'Find a comm line., Make yourself known., Discover what is needed or wanted., Do, produce and/or present it.') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000011-0000-0000-0000-000000000011', lesley_id, '2026-01-12', 23.0, 15.0, 53.3333, 'affluence', 'normal', 'Don’t change anything., Ethics are very mild : Dont freak out over little things, If a stat increased, what cased it to? how can we better incorporate it?, If a stat decreased, why and how can we fix it?') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000011-0000-0000-0000-000000000011', lesley_id, '2026-01-19', 13.0, 23.0, -43.4783, 'non_existence', 'danger', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000011-0000-0000-0000-000000000011', lesley_id, '2026-01-26', 9.0, 13.0, -30.7692, 'danger', 'emergency', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000011-0000-0000-0000-000000000011', lesley_id, '2026-02-02', 25.0, 9.0, 177.7778, 'affluence', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000011-0000-0000-0000-000000000011', lesley_id, '2026-02-09', 22.0, 25.0, -12.0, 'emergency', 'emergency', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000011-0000-0000-0000-000000000011', lesley_id, '2026-02-16', 15.0, 22.0, -31.8182, 'danger', 'emergency', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000011-0000-0000-0000-000000000011', lesley_id, '2026-02-23', 17.0, 15.0, 13.3333, 'normal', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000011-0000-0000-0000-000000000011', lesley_id, '2026-03-02', 5.0, 17.0, -70.5882, 'non_existence', 'danger', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000011-0000-0000-0000-000000000011', lesley_id, '2026-03-09', 5.0, 5.0, 0.0, 'emergency', 'emergency', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000011-0000-0000-0000-000000000011', lesley_id, '2026-03-16', 10.0, 5.0, 100.0, 'affluence', 'non_existence', 'If a stat increased, what cased it to? how can we better incorporate it?') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000011-0000-0000-0000-000000000011', lesley_id, '2026-03-16', 13.0, 10.0, 30.0, 'affluence', 'normal', 'If a stat increased, what cased it to? how can we better incorporate it?') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000012-0000-0000-0000-000000000012', lesley_id, '2025-12-29', 0.0, NULL, 0.0, 'normal', 'affluence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000012-0000-0000-0000-000000000012', lesley_id, '2026-01-05', 4.0, 0.0, 0.0, 'normal', 'non_existence', 'Find a comm line., Make yourself known., Discover what is needed or wanted., Do, produce and/or present it.') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000012-0000-0000-0000-000000000012', lesley_id, '2026-01-12', 9.0, 4.0, 125.0, 'affluence', 'normal', 'Don’t change anything., Ethics are very mild : Dont freak out over little things, If a stat increased, what cased it to? how can we better incorporate it?') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000012-0000-0000-0000-000000000012', lesley_id, '2026-01-19', 4.0, 9.0, -55.5556, 'non_existence', 'danger', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000012-0000-0000-0000-000000000012', lesley_id, '2026-01-26', 3.0, 4.0, -25.0, 'danger', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000012-0000-0000-0000-000000000012', lesley_id, '2026-02-02', 9.0, 3.0, 200.0, 'affluence', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000012-0000-0000-0000-000000000012', lesley_id, '2026-02-09', 12.0, 9.0, 33.3333, 'affluence', 'normal', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000012-0000-0000-0000-000000000012', lesley_id, '2026-02-16', 2.0, 12.0, -83.3333, 'non_existence', 'danger', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000012-0000-0000-0000-000000000012', lesley_id, '2026-02-23', 12.0, 2.0, 500.0, 'affluence', 'affluence', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000012-0000-0000-0000-000000000012', lesley_id, '2026-03-02', 3.0, 12.0, -75.0, 'non_existence', 'danger', NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000012-0000-0000-0000-000000000012', lesley_id, '2026-03-09', 7.0, 3.0, 133.3333, 'affluence', NULL, NULL) ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000012-0000-0000-0000-000000000012', lesley_id, '2026-03-16', 1.0, 7.0, -85.7143, 'non_existence', 'affluence', 'Change your operating basis') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;
  INSERT INTO stat_entries (stat_id, profile_id, week_start, value, previous_value, percent_change, auto_condition, self_condition, playbook_response) VALUES ('b0000012-0000-0000-0000-000000000012', lesley_id, '2026-03-16', 4.0, 1.0, 300.0, 'affluence', 'emergency', 'Change your operating basis') ON CONFLICT (stat_id, week_start) DO UPDATE SET value = EXCLUDED.value, previous_value = EXCLUDED.previous_value, percent_change = EXCLUDED.percent_change, auto_condition = EXCLUDED.auto_condition, self_condition = EXCLUDED.self_condition, playbook_response = EXCLUDED.playbook_response;

  -- ============================================================
  -- OIC Log Entries (35 records)
  -- ============================================================
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2025-12-30', 'Div 3', 'PR Officer', 'relaized theres duplicate GBP and deleted the unoptimized one associated with info@ssmilesdental.com. kept meezdds@gmail.com');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-01-01', 'Div 3 – Treasury', 'Multiple/Other', 'Increased fees by 5% across the board while keeping the Savings plan and NP special the same');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (lesley_id, '2026-01-07', 'Div 4 – Production', 'Scheduling Coordinator', 'Texting patients indicating I''m the schedule coordinator.');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-01-12', 'Div 6 – Public', 'Multiple/Other', 'New Signs on the windows');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-01-13', 'Div 6 – Public', 'Doctor', 'performed charitable work for Rafael Pinata');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (lesley_id, '2026-01-13', 'Div 2 – Communication', 'Receptionist', 'emergency patient policy (seen right away workflow)');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (lesley_id, '2026-01-14', 'Div 6 – Public', 'PR Officer', 'gave away 8 free baggies to sister in law to hand out at work');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (lesley_id, '2026-01-15', 'Div 4 – Production', 'Scheduling Coordinator', 'submitting recall appointment reminder one month');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (lesley_id, '2026-01-16', 'Div 4 – Production', 'Scheduling Coordinator', 'confirming appointments 2 day in advance + text &email 1 month out for recalls.');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (lesley_id, '2026-01-16', 'Div 4 – Production', 'Scheduling Coordinator', 'unconfirmed patients in the morning, get another call in the afternoon');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (lesley_id, '2026-01-28', 'Div 6 – Public', 'PR Officer', 'New side sign/ added Spanish boarding');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (lesley_id, '2026-01-28', 'Div 2 – Sales', 'Financial Coordinator', 'Showed patients pictures of calculus');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-01-29', 'Div 6 – Public', 'PR Officer', 'Distributed Tooth brush kits at a local business networking event');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-01-31', 'Div 6 – Public', 'PR Officer', 'increased google ads emergency patient campaign budget from 54$ to 60$ per day.');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-02-02', 'Div 1 – Communication', 'Receptionist', 'Evelis will be working 5 days instead of 4');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (lesley_id, '2026-02-05', 'Div 6 – Public', 'PR Officer', 'Health Fair 02/05/26');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-02-06', 'Div 1 – Communication', 'Receptionist', 'First BMO to Feb birthday patients');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (lesley_id, '2026-02-09', 'Div 2 – Sales', 'Treatment Coordinator', 'Lesley P. Treatment Coordintaor');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (lesley_id, '2026-02-09', 'Whole Practice', 'Multiple/Other', 'implimented finacial card on file policy');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (lesley_id, '2026-02-16', 'Div 2 – Sales', 'Treatment Coordinator', 'I gave Lesley P./ call list & daily schedule to follow.');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (lesley_id, '2026-02-23', 'Whole Practice', 'Multiple/Other', 'Dr. Shakally & Lesley attended MGE');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-02-23', 'Whole Practice', 'Multiple/Other', 'Did the formulas of conditions for the week in the car on the way back from California');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-02-24', 'Div 6 – Public', 'PR Officer', 'Increased LSA spend from 150$/week to 200$/week');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-02-25', 'Div 6 – Public', 'PR Officer', 'Recorded a video for the website');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-03-02', 'Div 2 – Sales', 'Treatment Coordinator', 'Lesley G Started assisting doctor in financial arrangements and closing of cases');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-03-03', 'Whole Practice', 'Multiple/Other', 'Had office meeting to discuss org board and hatting');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-03-03', 'Div 6 – Public', 'PR Officer', 'LED signs changed to promote 99$ new patient special');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-03-06', 'Div 1 – Communication', 'Receptionist', 'Bad interaction with disgruntled ex patient about her crown.');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-03-02', 'Div 2 – Sales', 'Treatment Coordinator', 'Corrected the problem associated with the Fees and raised prices by 5%');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-02-23', 'Div 6 – Public', 'PR Officer', 'Inacted the Care to Share Program');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-03-02', 'Whole Practice', 'Multiple/Other', 'Started organizing and doing the hats/checksheet system');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-03-16', 'Div 6 – Public', 'PR Officer', 'Re-instated the review games and added the spin wheel to it.');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-03-16', 'Div 2 – Sales', 'Treatment Coordinator', 'Lesley G went to California for MGE Courses');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-03-14', 'Div 6 – Public', 'PR Officer', 'for Emergency Campaign, Increase the max CPC bid limit from 7$ to 9$');
  INSERT INTO oic_log (profile_id, effective_date, area, post_affected, entry_text) VALUES (shakally_id, '2026-03-14', 'Div 6 – Public', 'PR Officer', 'For Google ads new patient campaign, increase max CPC bid limit from 6$ to 8$');

  RAISE NOTICE 'Historical import complete!';
END $$;